// Bundled demo data so the UI never looks empty even when the backend
// is offline. The shapes mirror the API responses defined in
// backend/app/schemas/. Real data flows in via lib/api.ts when the
// backend is reachable.

import type {
  DocumentListResponse,
  InsightsResponse,
  QueryResponse,
  RecentQuery,
  SystemStatusResponse,
} from "./types";

export const demoData = {
  documentList: <DocumentListResponse>{
    total: 8,
    documents: [
      {
        id: "doc_amm_xls_29",
        title: "Citation XLS AMM — Ch. 29 Hydraulic Power",
        type: "AMM",
        aircraft: "Citation XLS",
        source: "Operator Library",
        status: "indexed",
        pages: 412,
        size_mb: 38.2,
        uploaded_at: "2026-03-14T10:22:11Z",
        uploaded_by: "m.alvarez",
        tags: ["ATA 29", "hydraulics"],
      },
      {
        id: "doc_ipc_xls",
        title: "Citation XLS IPC — Rev 47",
        type: "IPC",
        aircraft: "Citation XLS",
        source: "Operator Library",
        status: "indexed",
        pages: 2184,
        size_mb: 126.7,
        uploaded_at: "2026-03-01T08:12:03Z",
        uploaded_by: "m.alvarez",
        tags: ["parts", "illustrated"],
      },
      {
        id: "doc_sb_king_air_b78",
        title: "King Air 350 SB-B78-14 — Bleed Air Overtemp Monitoring",
        type: "SB",
        aircraft: "King Air 350",
        source: "Manufacturer Bulletin",
        status: "indexed",
        pages: 12,
        size_mb: 1.4,
        uploaded_at: "2026-03-22T14:50:44Z",
        uploaded_by: "j.tanaka",
        tags: ["bleed air", "SB"],
      },
      {
        id: "doc_wo_n123xl_0418",
        title: "Work Order N123XL — WO-2026-0418",
        type: "WORK_ORDER",
        aircraft: "Citation XLS",
        source: "Maintenance Records",
        status: "indexed",
        pages: 8,
        size_mb: 0.9,
        uploaded_at: "2026-04-02T17:03:30Z",
        uploaded_by: "shop.floor",
        tags: ["N123XL"],
      },
      {
        id: "doc_logbook_n882gs",
        title: "Logbook — N882GS Gulfstream G200 (2024–2026)",
        type: "LOGBOOK",
        aircraft: "Gulfstream G200",
        source: "Maintenance Records",
        status: "indexed",
        pages: 186,
        size_mb: 6.1,
        uploaded_at: "2026-02-11T12:00:00Z",
        uploaded_by: "r.okonkwo",
        tags: ["G200"],
      },
      {
        id: "doc_trb_lj60_ata27",
        title: "Troubleshooting Record — Learjet 60 ATA 27",
        type: "TROUBLESHOOTING",
        aircraft: "Learjet 60",
        source: "Shop Records",
        status: "indexed",
        pages: 22,
        size_mb: 2.0,
        uploaded_at: "2026-03-05T09:18:00Z",
        uploaded_by: "p.kowalski",
        tags: ["ATA 27"],
      },
      {
        id: "doc_inspection_xls",
        title: "Citation XLS Inspection Program — Phase C",
        type: "INSPECTION_PROGRAM",
        aircraft: "Citation XLS",
        source: "Operator Library",
        status: "indexed",
        pages: 96,
        size_mb: 4.3,
        uploaded_at: "2026-01-18T11:11:11Z",
        uploaded_by: "m.alvarez",
        tags: ["phase C"],
      },
      {
        id: "doc_parts_catalog_bleedair",
        title: "Parts Catalog Excerpt — Bleed Air Components",
        type: "PARTS_CATALOG",
        aircraft: "King Air 350",
        source: "Parts Vendor",
        status: "processing",
        pages: 44,
        size_mb: 3.8,
        uploaded_at: "2026-04-06T22:44:01Z",
        uploaded_by: "parts.desk",
        tags: ["bleed air"],
      },
    ],
  },

  recentQueries: <RecentQuery[]>[
    {
      id: "q_hyd_fluct_xls",
      question:
        "What are the likely causes of hydraulic pressure fluctuation on the Citation XLS?",
      created_at: "2026-04-07T15:42:11Z",
      confidence: "high",
    },
    {
      id: "q_bleed_overtemp_trend",
      question:
        "Find recurring writeups related to bleed air overtemp across the King Air 350 fleet.",
      created_at: "2026-04-06T09:10:00Z",
      confidence: "high",
    },
    {
      id: "q_lj60_aileron",
      question: "Show similar troubleshooting on Learjet 60 aileron trim runaway.",
      created_at: "2026-04-04T13:22:01Z",
      confidence: "medium",
    },
    {
      id: "q_g200_inspections",
      question: "Which inspections are due in the next 30 days for N882GS?",
      created_at: "2026-04-03T11:01:01Z",
      confidence: "medium",
    },
  ],

  exampleQueryResponse: <QueryResponse>{
    question:
      "What are the likely causes of hydraulic pressure fluctuation on the Citation XLS?",
    answer:
      "Hydraulic pressure fluctuation on the Citation XLS typically traces to one of four subsystems: a failing engine-driven pump, air entrainment in the reservoir, a degraded pressure regulator, or a leaking priority valve. The AMM Ch. 29 inspection flow recommends starting with reservoir fluid level and aeration check, then a pump case-drain flow test before condemning the regulator. Three prior work orders on N123XL show the reservoir servicing path resolved the symptom on two aircraft within this operator's fleet.",
    sections: [
      {
        heading: "Probable causes",
        bullets: [
          "Engine-driven pump wear (pump case drain flow out of limits)",
          "Air entrained in hydraulic reservoir after servicing",
          "Pressure regulator drift",
          "Internal leak at the priority valve",
        ],
      },
      {
        heading: "Recommended actions",
        bullets: [
          "Verify reservoir fluid level and aeration per AMM 29-10-00",
          "Run pump case-drain flow test per AMM 29-11-05",
          "Inspect pressure regulator adjustment per AMM 29-12-02",
          "Review work order history for repeated servicing on the same tail",
        ],
      },
      {
        heading: "Referenced procedures",
        bullets: [
          "AMM 29-10-00 — Hydraulic power general",
          "AMM 29-11-05 — Pump case-drain test",
          "AMM 29-12-02 — Pressure regulator adjustment",
        ],
      },
    ],
    citations: [
      {
        document_id: "doc_amm_xls_29",
        document_title: "Citation XLS AMM — Ch. 29 Hydraulic Power",
        document_type: "AMM",
        page: 14,
        snippet:
          "Pump case-drain flow shall be measured with reservoir at full and system pressurized to 3000 psi.",
        score: 0.92,
        lane: "manual",
      },
      {
        document_id: "doc_amm_xls_29",
        document_title: "Citation XLS AMM — Ch. 29 Hydraulic Power",
        document_type: "AMM",
        page: 27,
        snippet:
          "Air entrainment in the reservoir may present as pressure oscillation during gear retraction.",
        score: 0.88,
        lane: "manual",
      },
      {
        document_id: "doc_wo_n123xl_0418",
        document_title: "Work Order N123XL — WO-2026-0418",
        document_type: "WORK_ORDER",
        page: 3,
        snippet:
          "Hydraulic pressure fluctuation on climb. Serviced reservoir, bled system, ops-checked satisfactory.",
        score: 0.81,
        lane: "history",
      },
    ],
    related_documents: [
      { id: "doc_ipc_xls", title: "Citation XLS IPC — Rev 47", type: "IPC" },
      {
        id: "doc_inspection_xls",
        title: "Citation XLS Inspection Program — Phase C",
        type: "INSPECTION_PROGRAM",
      },
    ],
    entities: [
      { kind: "aircraft", value: "Citation XLS" },
      { kind: "ata", value: "ATA 29" },
      { kind: "part_number", value: "3214091-01" },
      { kind: "tail_number", value: "N123XL" },
    ],
    confidence: {
      score: 0.86,
      label: "high",
      reason: "Five corroborating chunks across AMM and maintenance history.",
    },
    followups: [
      "Show the exact AMM 29-11-05 pump case-drain flow procedure.",
      "List all prior hydraulic write-ups on N123XL in the last 12 months.",
      "Which parts are required to rebuild the hydraulic pressure regulator?",
    ],
    latency_ms: 184,
  },

  insights: <InsightsResponse>{
    recurring_clusters: [
      {
        id: "cl_bleed_overtemp",
        title: "Bleed air overtemp — right-hand duct sensor",
        aircraft: "King Air 350",
        ata: "ATA 36",
        count_90d: 7,
        aircraft_count: 4,
        trend: "rising",
        last_occurred: "2026-04-05",
        severity: "medium",
        notes: "Concentrated on aircraft without SB-B78-14 compliance.",
      },
      {
        id: "cl_aileron_trim",
        title: "Aileron trim runaway — intermittent",
        aircraft: "Learjet 60",
        ata: "ATA 27",
        count_90d: 4,
        aircraft_count: 3,
        trend: "flat",
        last_occurred: "2026-03-29",
        severity: "medium",
        notes: "Shop troubleshooting record points to trim actuator harness chafing.",
      },
      {
        id: "cl_hyd_press_fluct",
        title: "Hydraulic pressure fluctuation on climb",
        aircraft: "Citation XLS",
        ata: "ATA 29",
        count_90d: 5,
        aircraft_count: 2,
        trend: "falling",
        last_occurred: "2026-04-02",
        severity: "low",
        notes: "Majority resolved with reservoir servicing and bleed.",
      },
    ],
    ata_hotspots: [
      { ata: "ATA 36", label: "Bleed Air", count_90d: 12, delta_pct: 34 },
      { ata: "ATA 29", label: "Hydraulic Power", count_90d: 9, delta_pct: -12 },
      { ata: "ATA 27", label: "Flight Controls", count_90d: 6, delta_pct: 5 },
      { ata: "ATA 32", label: "Landing Gear", count_90d: 5, delta_pct: 0 },
      { ata: "ATA 77", label: "Engine Indicating", count_90d: 4, delta_pct: 22 },
    ],
    fleet_widgets: [
      {
        id: "w_deferred_items",
        label: "Deferred items",
        value: 14,
        unit: "items",
        trend: "stable",
        detail: "3 high-impact, 11 low-impact across 6 aircraft.",
      },
      {
        id: "w_due_inspections",
        label: "Inspections due in 30 days",
        value: 8,
        unit: "inspections",
        trend: "rising",
        detail: "5 Phase C, 3 Phase D across the Citation fleet.",
      },
      {
        id: "w_parts_on_order",
        label: "Parts on order",
        value: 23,
        unit: "line items",
        trend: "stable",
        detail: "2 AOG-critical, 21 routine replenishment.",
      },
      {
        id: "w_docs_indexed",
        label: "Documents indexed",
        value: 8,
        unit: "docs",
        trend: "rising",
        detail: "8 demo documents loaded.",
      },
    ],
  },

  systemStatus: <SystemStatusResponse>{
    components: [
      { id: "api", label: "API", status: "healthy" },
      { id: "ingestion", label: "Ingestion queue", status: "healthy" },
      { id: "ocr", label: "OCR worker", status: "degraded" },
      { id: "embeddings", label: "Embedding worker", status: "healthy" },
      { id: "vector", label: "Vector index", status: "healthy" },
      { id: "provider", label: "AI provider (stub)", status: "healthy" },
    ],
    logs: [
      {
        ts: "2026-04-08T08:13:12Z",
        stage: "embedder",
        doc: "doc_parts_catalog_bleedair",
        status: "queued",
        detail: "waiting for embedding worker",
      },
      {
        ts: "2026-04-08T08:13:01Z",
        stage: "chunker",
        doc: "doc_parts_catalog_bleedair",
        status: "ok",
        detail: "126 chunks produced",
      },
      {
        ts: "2026-04-08T08:12:49Z",
        stage: "document_classifier",
        doc: "doc_parts_catalog_bleedair",
        status: "ok",
        detail: "classified as PARTS_CATALOG",
      },
      {
        ts: "2026-04-08T08:12:44Z",
        stage: "pdf_parser",
        doc: "doc_parts_catalog_bleedair",
        status: "ok",
        detail: "44 pages extracted",
      },
      {
        ts: "2026-04-08T07:44:11Z",
        stage: "ocr_processor",
        doc: "doc_logbook_n882gs",
        status: "ok",
        detail: "14 pages OCRed, 2 low-confidence",
      },
    ],
    version: "0.1.0",
    demo_mode: true,
    ai_provider: "stub",
  },
};
